### ISSUE TITLE
Cannot enable plugin.

### ISSUE THREAD

**Issue by pocketkings719** [grandwazir/StarterKit#12]
Config:

debugging: true
kit:
  backpack:
    ==: InventoryKit
    '3':
      ==: org.bukkit.inventory.ItemStack
      type: IRON_AXE
    '2':
      ==: org.bukkit.inventory.ItemStack
      type: IRON_SPADE
    '1':
      ==: org.bukkit.inventory.ItemStack
      type: IRON_PICKAXE
    '0':
      ==: org.bukkit.inventory.ItemStack
      type: IRON_SWORD
    '4':
      ==: org.bukkit.inventory.ItemStack
      type: COOKED_BEEF
      amount: 5

Log:

2012-05-18 20:30:33 [SEVERE] Error occurred while enabling StarterKit v1.1.2 (Is it up to date?)
java.lang.NullPointerException
    at name.richardson.james.bukkit.starterkit.StarterKitConfiguration.getItemCount(StarterKitConfiguration.java:53)
    at name.richardson.james.bukkit.starterkit.StarterKit.getFormattedKitCount(StarterKit.java:42)
    at name.richardson.james.bukkit.starterkit.StarterKit.loadConfiguration(StarterKit.java:85)
    at name.richardson.james.bukkit.starterkit.StarterKit.onEnable(StarterKit.java:58)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:256)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:238)
    at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:372)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:359)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:188)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:423)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)

**Comment by grandwazir** [comment]
Clear your config then reopen this issue if the problem persists.
