### ISSUE TITLE
Error on Startup

### ISSUE THREAD

**Issue by ghost** [grandwazir/StarterKit#13]
Been looking for a mod that does something like this.. However so far none of them seem to work right.. 

After Enabling The Mod on the server.. i get the following error in Console.

12:25:44 [INFO] [StarterKit] Enabling StarterKit v1.0.0
12:25:44 [SEVERE] Error occurred while enabling StarterKit v1.0.0 (Is it up to d
ate?)
java.lang.NoClassDefFoundError: org/bukkit/event/player/PlayerListener
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:41)
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoad
er.java:234)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:37)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:29)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at name.richardson.james.bukkit.starterkit.StarterKit.loadListeners(Star
terKit.java:90)
        at name.richardson.james.bukkit.starterkit.StarterKit.onEnable(StarterKi
t.java:64)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader
.java:336)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage
r.java:381)
        at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:256)
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:238
)
        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:372)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:359)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:188)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:423)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
Caused by: java.lang.ClassNotFoundException: org.bukkit.event.player.PlayerListe
ner
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:41)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:29)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 27 more

**Comment by grandwazir** [comment]
You are not using the latest version. Try downloading the latest
version and it should work just fine.

**Comment by ghost** [comment]
Thanks! Worked like a charm.. now to see if i can get it to work..
