### ISSUE TITLE
 [SEVERE] Error occurred while enabling StarterKit v1.2.1 (Is it up to date?)

### ISSUE THREAD

**Issue by ScottSpittle** [grandwazir/StarterKit#15]
18:38:54 [INFO] [StarterKit] Enabling StarterKit v1.2.1
18:38:54 [SEVERE] Error occurred while enabling StarterKit v1.2.1 (Is it up to date?)
java.lang.NullPointerException
        at name.richardson.james.bukkit.starterkit.StarterKitConfiguration.getItemCount(StarterKitConfiguration.java:49)
        at name.richardson.james.bukkit.starterkit.StarterKit.getFormattedKitCount(StarterKit.java:41)
        at name.richardson.james.bukkit.starterkit.StarterKit.loadConfiguration(StarterKit.java:58)
        at name.richardson.james.bukkit.utilities.plugin.SkeletonPlugin.onEnable(SkeletonPlugin.java:167)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
        at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:257)
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:239)
        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:383)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:370)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:199)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:434)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)

**Comment by grandwazir** [comment]
Closed this by mistake. Try clearing your configuration then reloading the plugin,
