### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Nightreaver** [grandwazir/StarterKit#25]
This server is running CraftBukkit version git-MCPC-Plus-jenkins-MCPC-Plus-Legacy-602 (MC: 1.5.2) (Implementing API version 1.5.2-R1.1-SNAPSHOT)

[SEVERE] Could not load 'plugins\starter-kit-1.3.3.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.util.MissingResourceException: Can't find localisation/messages bundle
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:174)
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:307)
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:231)
    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.loadPlugins(CraftServer.java:265)
    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.<init>(CraftServer.java:243)
    at net.minecraft.server.management.ServerConfigurationManager.<init>(ServerConfigurationManager.java:128)
    at net.minecraft.server.dedicated.DedicatedPlayerList.<init>(SourceFile:11)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:158)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:574)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
Caused by: java.util.MissingResourceException: Can't find localisation/messages bundle
    at java.util.logging.Logger.setupResourceInfo(Unknown Source)
    at java.util.logging.Logger.<init>(Unknown Source)
    at java.util.logging.Logger.<init>(Unknown Source)
    at name.richardson.james.bukkit.starterkit.utilities.logging.PluginLogger.<init>(PluginLogger.java:65)
    at name.richardson.james.bukkit.starterkit.utilities.logging.PluginLogger.getLogger(PluginLogger.java:44)
    at name.richardson.james.bukkit.starterkit.utilities.logging.PluginLogger.getLogger(PluginLogger.java:37)
    at name.richardson.james.bukkit.starterkit.utilities.plugin.AbstractPlugin.<init>(AbstractPlugin.java:50)
    at name.richardson.james.bukkit.starterkit.StarterKit.<init>(StarterKit.java:40)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:170)
    ... 9 more

**Comment by grandwazir** [comment]
This should not happen any more as the bug is now fixed upstream. Thanks for reporting it.
