### ISSUE TITLE
Following error on startup.

### ISSUE THREAD

**Issue by mkromann** [grandwazir/StarterKit#5]
`2012-04-24 13:09:21 [SEVERE] Error occurred while enabling StarterKit v1.1.0 (Is it up to date?)
java.lang.NullPointerException
    at name.richardson.james.bukkit.starterkit.StarterKitConfiguration.getItemCount(StarterKitConfiguration.java:78)
    at name.richardson.james.bukkit.starterkit.StarterKit.getFormattedKitCount(StarterKit.java:96)
    at name.richardson.james.bukkit.starterkit.StarterKit.loadConfiguration(StarterKit.java:79)
    at name.richardson.james.bukkit.starterkit.StarterKit.onEnable(StarterKit.java:52)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:250)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:232)
    at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:371)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:358)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:187)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:422)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)`

I used the symbolic link for the newest version.

**Comment by grandwazir** [comment]
This issue is now fixed in StarterKit v1.1.1. Thank you for reporting the issue.
