### ISSUE TITLE
Problems with cb++ 1.2.5

### ISSUE THREAD

**Issue by jinko132** [grandwazir/StarterKit#6]
after i made a sk with /sk save and restart server i get this.

2012-04-25 11:47:35 [SEVERE] Could not call method 'public static name.richardson.james.bukkit.starterkit.ArmourKit name.richardson.james.bukkit.starterkit.ArmourKit.deserialize(java.util.Map)' of class name.richardson.james.bukkit.starterkit.ArmourKit for deserialization
java.lang.IndexOutOfBoundsException: Index: 3, Size: 0
    at java.util.ArrayList.rangeCheckForAdd(ArrayList.java:612)
    at java.util.ArrayList.add(ArrayList.java:426)
    at name.richardson.james.bukkit.starterkit.ArmourKit.deserialize(ArmourKit.java:40)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:66)
    at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:108)
    at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:180)
    at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:35)
    at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:183)
    at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:326)
    at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:143)
    at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:307)
    at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:459)
    at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26)
    at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:183)
    at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:326)
    at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:143)
    at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:307)
    at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:459)
    at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26)
    at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:183)
    at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:142)
    at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:128)
    at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:480)
    at org.yaml.snakeyaml.Yaml.load(Yaml.java:399)
    at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53)
    at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:143)
    at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:109)
    at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:177)
    at name.richardson.james.bukkit.utilities.configuration.AbstractConfiguration.load(AbstractConfiguration.java:58)
    at name.richardson.james.bukkit.utilities.configuration.AbstractConfiguration.<init>(AbstractConfiguration.java:44)
    at name.richardson.james.bukkit.starterkit.StarterKitConfiguration.<init>(StarterKitConfiguration.java:34)
    at name.richardson.james.bukkit.starterkit.StarterKit.loadConfiguration(StarterKit.java:81)
    at name.richardson.james.bukkit.starterkit.StarterKit.onEnable(StarterKit.java:58)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:383)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:355)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:337)
    at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:420)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:407)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:224)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:475)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
2012-04-25 11:47:35 [SEVERE] Error occurred while enabling StarterKit v1.1.1 (Is it up to date?)
java.lang.NullPointerException
    at name.richardson.james.bukkit.starterkit.StarterKitConfiguration.getItemCount(StarterKitConfiguration.java:53)
    at name.richardson.james.bukkit.starterkit.StarterKit.getFormattedKitCount(StarterKit.java:42)
    at name.richardson.james.bukkit.starterkit.StarterKit.loadConfiguration(StarterKit.java:85)
    at name.richardson.james.bukkit.starterkit.StarterKit.onEnable(StarterKit.java:58)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:383)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:355)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:337)
    at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:420)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:407)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:224)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:475)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)

**Comment by grandwazir** [comment]
Thank you for reporting this issue. It is now fixed in the version 1.1.2.
