### ISSUE TITLE
StarterKit crashes on server restart

### ISSUE THREAD

**Issue by blacktowercem** [grandwazir/StarterKit#7]
Using Bukkit 1.2.5-R1.0 and 1.2.5-R1.2 - StarterKit 1.1.1

Initial install and setup seems to go as normal.  
Saving a starter kit setup, the conf.yml file is as follows:

---

debugging: true
kit:
  backpack:
    ==: InventoryKit
    '3':
      ==: org.bukkit.inventory.ItemStack
      type: STONE_AXE
    '2':
      ==: org.bukkit.inventory.ItemStack
      type: STONE_PICKAXE
    '10':
      ==: org.bukkit.inventory.ItemStack
      type: RAW_BEEF
      amount: 3
    '1':
      ==: org.bukkit.inventory.ItemStack
      type: STONE_SPADE
    '0':
      ==: org.bukkit.inventory.ItemStack
      type: STONE_SWORD
      damage: 23
    '7':
      ==: org.bukkit.inventory.ItemStack
      type: REDSTONE_TORCH_ON
      amount: 64
    '6':
      ==: org.bukkit.inventory.ItemStack
      type: ARROW
      amount: 61
    '5':
      ==: org.bukkit.inventory.ItemStack
      type: BOW
      damage: 153
    '4':
      ==: org.bukkit.inventory.ItemStack
      type: STONE_HOE
    '18':
      ==: org.bukkit.inventory.ItemStack
      type: SEEDS
      amount: 3
    '9':
      ==: org.bukkit.inventory.ItemStack
      type: LEATHER
      amount: 2
    '8':
      ==: org.bukkit.inventory.ItemStack
      type: BREAD
      amount: 16
  armour:
    ==: ArmourKit
    '3':
      ==: org.bukkit.inventory.ItemStack
      type: CHAINMAIL_HELMET
    '2':
      ==: org.bukkit.inventory.ItemStack
      type: CHAINMAIL_CHESTPLATE
    '1':
      ==: org.bukkit.inventory.ItemStack
      type: CHAINMAIL_LEGGINGS
    '0':
      ==: org.bukkit.inventory.ItemStack
      type: CHAINMAIL_BOOTS

---
## When server restarts, it changes the conf.yml file to this:

debugging: true
kit:
  backpack:
    ==: InventoryKit
    '3':
      ==: org.bukkit.inventory.ItemStack
      type: STONE_AXE
    '2':
      ==: org.bukkit.inventory.ItemStack
      type: STONE_PICKAXE
    '10':
      ==: org.bukkit.inventory.ItemStack
      type: RAW_BEEF
      amount: 3
    '1':
      ==: org.bukkit.inventory.ItemStack
      type: STONE_SPADE
    '0':
      ==: org.bukkit.inventory.ItemStack
      type: STONE_SWORD
      damage: 23
    '7':
      ==: org.bukkit.inventory.ItemStack
      type: REDSTONE_TORCH_ON
      amount: 64
    '6':
      ==: org.bukkit.inventory.ItemStack
      type: ARROW
      amount: 61
    '5':
      ==: org.bukkit.inventory.ItemStack
      type: BOW
      damage: 153
    '4':
      ==: org.bukkit.inventory.ItemStack
      type: STONE_HOE
    '18':
      ==: org.bukkit.inventory.ItemStack
      type: SEEDS
      amount: 3
    '9':
      ==: org.bukkit.inventory.ItemStack
      type: LEATHER
      amount: 2
    '8':
      ==: org.bukkit.inventory.ItemStack
      type: BREAD
## It also throws there errors in the console:

16:32:33 [SEVERE] Could not call method 'public static name.richardson.james.bukkit.starterkit.ArmourKit name.richardson.james.bukkit.starterkit.ArmourKit.deserialize(java.util.Map)' of class name.richardson.james.bukkit.starterkit.ArmourKit for deserialization
java.lang.IndexOutOfBoundsException: Index: 3, Size: 0
    at java.util.ArrayList.add(ArrayList.java:367)
    at name.richardson.james.bukkit.starterkit.ArmourKit.deserialize(ArmourKit.java:40)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:66)
    at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:108)
    at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:180)
    at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:35)
    at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:183)
    at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:326)
    at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:143)
    at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:307)
    at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:459)
    at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26)
    at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:183)
    at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:326)
    at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:143)
    at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:307)
    at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:459)
    at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26)
    at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:183)
    at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:142)
    at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:128)
    at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:480)
    at org.yaml.snakeyaml.Yaml.load(Yaml.java:399)
    at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53)
    at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:143)
    at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:109)
    at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:177)
    at name.richardson.james.bukkit.utilities.configuration.AbstractConfiguration.load(AbstractConfiguration.java:58)
    at name.richardson.james.bukkit.utilities.configuration.AbstractConfiguration.<init>(AbstractConfiguration.java:44)
    at name.richardson.james.bukkit.starterkit.StarterKitConfiguration.<init>(StarterKitConfiguration.java:34)
    at name.richardson.james.bukkit.starterkit.StarterKit.loadConfiguration(StarterKit.java:81)
    at name.richardson.james.bukkit.starterkit.StarterKit.onEnable(StarterKit.java:58)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:250)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:232)
    at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:371)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:358)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:187)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:422)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
16:32:33 [SEVERE] Error occurred while enabling StarterKit v1.1.1 (Is it up to date?)
java.lang.NullPointerException
    at name.richardson.james.bukkit.starterkit.StarterKitConfiguration.getItemCount(StarterKitConfiguration.java:53)
    at name.richardson.james.bukkit.starterkit.StarterKit.getFormattedKitCount(StarterKit.java:42)
    at name.richardson.james.bukkit.starterkit.StarterKit.loadConfiguration(StarterKit.java:85)
    at name.richardson.james.bukkit.starterkit.StarterKit.onEnable(StarterKit.java:58)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:250)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:232)
    at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:371)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:358)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:187)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:422)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)

Unable to recover from the console errors and have to delete the conf.yml file.

**Comment by blacktowercem** [comment]
Sorry, duplicate to previously reported issue - didn't see that one first.

**Comment by grandwazir** [comment]
Thank you for making the bug report anyway. I was useful to have a sample configuration that is known to cause the issue.
