### ISSUE TITLE
something wrong with new version?

### ISSUE THREAD

**Issue by drdeft** [grandwazir/StarterKit#8]
CraftBukkitPlusPlus 1.2.5 build 198

2012-04-29 23:05:59 [SEVERE] Error occurred while enabling StarterKit v1.1.2 (Is it up to date?)
java.util.MissingResourceException: Can't find bundle for base name starterkit-localisation, locale en_US
    at java.util.ResourceBundle.throwMissingResourceException(Unknown Source)
    at java.util.ResourceBundle.getBundleImpl(Unknown Source)
    at java.util.ResourceBundle.getBundle(Unknown Source)
    at name.richardson.james.bukkit.utilities.plugin.SimplePlugin.setResourceBundle(SimplePlugin.java:222)
    at name.richardson.james.bukkit.starterkit.StarterKit.onEnable(StarterKit.java:57)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:383)
    at im.mcft.pluginreloader.PluginReloader.loadPlugin(PluginReloader.java:250)
    at im.mcft.pluginreloader.PluginReloader.onCommand(PluginReloader.java:86)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:166)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:636)
    at org.bukkit.craftbukkit.CraftServer.dispatchServerCommand(CraftServer.java:632)
    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:671)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:640)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:506)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)

**Comment by grandwazir** [comment]
This should not happen. If the plugin can not find a localisation for your language it should fall back to using the default messages. I notice you are using CraftBukkitPlusPlus. Could you try again using the official recommended build and then let me know if the problem persists?

**Comment by grandwazir** [comment]
Closing this issue after receiving no reply.
